### ISSUE TITLE
Change "Playing" to "Listening to"

### ISSUE THREAD

**Issue by supra107** [TheQwertiest/foo_discord_rich#2]
I have noticed that it is possible to change it to this, and I think it would fit better, considering some translations implicate "Playing" as playing a game, for example in the Polish translation "Playing" is translated to "W grze" which means "Ingame", and that doesn't make sense.

**Comment by TheQwertiest** [comment]
Regretfully, I can do nothing about - it's a limitation of Discord API.
If I could I would make this pluging look the same as Spotify integration, but, alas, Discord developers are not yet ready to give such tools to 3rd parties =(

**Comment by Dogeisbest** [comment]
@supra107 you actually can't do that right now. The only possible way (as @TheQwertiest said) is Spotify. You can do "Listening to" and "Watching" but only with bots, and self-botting is against Discord's ToS, so you cannot do so.
![image](https://user-images.githubusercontent.com/29840719/50399591-87480b80-074e-11e9-8462-8c8beaea212e.png)
![image](https://user-images.githubusercontent.com/29840719/50399598-9038dd00-074e-11e9-8ae2-1ebc2745ff6c.png)

**Comment by TheQwertiest** [comment]
Closing this issue, since nothing can be done here.

**Comment by TheQwertiest** [comment]
Somewhat related: #6

**Comment by MrMightyNighty** [comment]
Discord RPC is deprecated in favor of GameSDK. "Replacement functionality for the Rich Presence SDK can be found in the [Activity Manager](https://discord.com/developers/docs/game-sdk/activities) of that SDK."

With the new SDK it is possible to change the [activity](https://discord.com/developers/docs/topics/gateway#activity-object-activity-types) to "Listening"

**Comment by TheQwertiest** [comment]
Thanks for the tip!

**Comment by miitchel** [comment]
> 
> 
> Thanks for the tip!

do you think it will be added?

**Comment by kotflinte** [comment]
would like to now too 

👍

**Comment by Jean-The-Creator** [comment]
When will this be in the plugin?

**Comment by LLinoor** [comment]
GameSDK allows to define an activity type (Play, Listen, Watch, ...) but for now the feature is not supported.
The feature is in the documentation since 2019 but still not usable in 2021, so I think we can wait a long time

Source: discord/gamesdk-and-dispatch#49 and discord/discord-api-docs#1002

**Comment by TheQwertiest** [comment]
Yup, that's the same conclusion I've reached.
This SDK doesn't give any more relevant features than the SDK used in the component. All extra features are all about more fine-grained monitoring of Discord events, but there are no additional features for modifying the Rich Presence.

**Comment by codefreak558** [comment]
Hi I took on how you'd be able to change it from "Playing" to "Listening" and what I found in the Game SDK is a Data Module that handles the type of Rich Presence that will appear in discord.

https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum

This is taken from the Discord Game SDK

**ActivityType Enum**
<html><body>


name | Value
-- | --
Playing | 0
Streaming | 1
Listening | 2
Watching | 3
Custom | 4
Competing | 5


</body>
</html>

**Comment by BobbyWibowo** [comment]
^ The same documentation says this under the table:
> `ActivityType` is strictly for the purpose of handling events that you receive from Discord; though the SDK/our API will not reject a payload with an `ActivityType` sent, it will be discarded and will not change anything in the client.

**Comment by tunip3** [comment]
I modified ciders vencord plugin to add support for doing this with the extension https://github.com/tunip3/Vencord-foobar/blob/main/README.md

**Comment by tunip3** [comment]
![image](https://github.com/TheQwertiest/foo_discord_rich/assets/26260613/49385328-fbbe-48d5-9dcd-428fd9d75924)

**Comment by shirafukayayoi** [comment]
> I modified ciders vencord plugin to add support for doing this with the extension https://github.com/tunip3/Vencord-foobar/blob/main/README.md

Hello.
I tried to find out how to achieve the above status.
In order to achieve this status, you need to download a software called "Vencord" that almost violates Discord's terms and conditions.
The reason why you need to download it is to use "richerCider" in Vencord's Plugin.
This seems to automatically change the status of the specified application ID to "Playing music".
If you look at the original code, it seems to use a technique used in a software called "cider".
"https://github.com/tunip3/Vencord-foobar/blob/main/richerCider.desktop.tsx"
It may be possible to create a plug-in that allows you to "play music" without using Vencord by using "cider" technology.
I don't have much knowledge, so it might be difficult to make one, but I'd like to try some.
*This text uses Google Translate.
![image](https://github.com/TheQwertiest/foo_discord_rich/assets/121822905/c3c3b738-8c0f-4b5a-a588-c3b43560cc25)
![image](https://github.com/TheQwertiest/foo_discord_rich/assets/121822905/a4701225-7403-48f6-a053-8a58a91f31b5)

**Comment by Otuxam3** [comment]
Hello everyone, I come with good news (just like for album art issue haha).

https://github.com/discord/discord-api-docs/pull/7033 is about to get merged (in a matter of days I guess?) making it easier and without hacks like Vencord and the like.

GameSDK getting the one getting deprecated and probably even discontinued instead of the original RPC API, the command is as simple as adding the `type: 2` in `activity` object.

If this allows for the time bar to also appear... that'd be awesome but it's just me dreaming here.

**Comment by TheQwertiest** [comment]
Great find! And this time it *does* work!
![image](https://github.com/user-attachments/assets/cf0286a8-493b-4ba7-8889-f4cb92af9cff)

**Comment by asterryplace** [comment]
> ![image](https://private-user-images.githubusercontent.com/26260613/332992924-49385328-fbbe-48d5-9dcd-428fd9d75924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjIzNzQsIm5iZiI6MTczMjM2MjA3NCwicGF0aCI6Ii8yNjI2MDYxMy8zMzI5OTI5MjQtNDkzODUzMjgtZmJiZS00OGQ1LTlkY2QtNDI4ZmQ5ZDc1OTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDExNDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MTBhMjI4NGViODE4ZGY5ZjVhMDRjNzlmOWYzZTg3ZWMxMDZiMDU1OGM4NTkyMjk5ODRlYzFkMzA5NjU1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ang9X_SIcTz_BkI386rQFMaPvBLLngHnA1OVq_P7I6M)

Randomly butting in to say, this seems to be absolutely broken when using ARMcord; similarly, fdr doesn't seem to work with it either which is a bit of a bummer

**Comment by Dogeisbest** [comment]
@asterryplace I believe this is an issue with what ARMcord _actually is_, since it's just an Electron wrapper for the website version of Discord. Unless they have support for the Game SDK (which I believe _some_ web-wrappers do but I may be wrong) then it likely wouldn't work

**Comment by brw** [comment]
They use [arRPC](https://arrpc.openasar.dev), which ArmCord supports as well (if we're talking about the same ArmCord here, the image is broken/inaccessible so I can't see the exact problem)

**Comment by asterryplace** [comment]
They do have in-built arRPC, but I honestly didn't manage to make it work nicely with this one ^^" just thought I'd leave a note for other armcord users in case they come across this comp, since when I used it on my PC with a Vencord fork it worked super neatly.
