### ISSUE TITLE
Foobar 2.0 64-bit

### ISSUE THREAD

**Issue by ShinGitS** [TheQwertiest/foo_discord_rich#39]
With the release of foobar 2.0 beta, there is a 64-bit build released as well.  While the 32 bit version can use all existing components,  the 64-bit requires the components to be re-written for compatibility.

**Comment by iGom** [comment]
.

**Comment by tort-oise** [comment]
Bump. If 2.0 is merging completely to 64-bit, creating compatibility for components such as this is required.

**Comment by dyni00** [comment]
up! **please update for 64bit**

**Comment by tort-oise** [comment]
Bump, again! Doesn't get enough attention.

**Comment by dyni00** [comment]
bbbuuummp

**Comment by kozaka-tv** [comment]
Boo(mp)

**Comment by PrincessAkira** [comment]
Boomp

**Comment by fritojay** [comment]
I built a 64-bit version here https://github.com/fritojay/foo_discord_rich/releases/tag/v1.2.1: I am not a C++ expert by any means.

**Comment by PrincessAkira** [comment]
> I built a 64-bit version here https://github.com/fritojay/foo_discord_rich/releases/tag/v1.2.1: I am not a C++ expert by any means.

OMFG UR A LEGEND IT WORKS

**Comment by kanishknishar** [comment]
> I built a 64-bit version here https://github.com/fritojay/foo_discord_rich/releases/tag/v1.2.1: I am not a C++ expert by any means.

Thank you so much for creating a 64-bit version. Greatly appreciated!

**Comment by JDJGInc** [comment]
I hope it comes to the addon soon, I Cannot wait for a reply :)

**Comment by JDJGInc** [comment]
ooh 64 bit support?

**Comment by Robby-** [comment]
Is it possible to merge both the Win32 and x64 version into one fb2k-component file?

Plugins supporting both architectures are supposed to package the plugin DLL files into one fb2k-component file, like so:
- The 32-bit DLL in the root of the plugin folder
- The 64-bit DLL in a sub-folder called `x64`.

This is so that people still on the 32-bit version of foobar2000 can later simply install the 64-bit version and it will automatically pick up the 64-bit DLL inside that `x64` sub-folder.

**Comment by TheQwertiest** [comment]
Didn't know that, thank for the info!
