### ISSUE TITLE
Foobar2000 won't tap into the Discord activity

### ISSUE THREAD

**Issue by LastWayGH** [TheQwertiest/foo_discord_rich#48]
I've tried installing both foo_discord_rich.fb2k-component and foo_discord_rich-Win32.fb2k-component with both having succesfully loaded onto foobar [v1.6.16] but have failed to show up on Discord [Stable 199933 (db1e138)].

Here's a screenshot if it helps:
![image](https://github.com/TheQwertiest/foo_discord_rich/assets/119768350/ba6fa137-0d71-43bc-8c25-378c94a5d6d4)

Do I have to replace the Discord application token, or it some other issue?

**Comment by JomSpoons** [comment]
You're in luck then, because I actually did manage to figure it out a few hours ago. For whatever reason, doing a portable install of fb2k and adding foo_discord_rich to it (I followed [this guide](https://www.reddit.com/r/foobar2000/comments/ibznvk/comment/g233p1w/)) makes it work again. Not only that, once it started working, I went back to my main install of fb2k and that shockingly worked again as well. I've not had any issues since. I have no idea why this happened but hopefully the solution works for others as well.
