### ISSUE TITLE
Track Duration setting not available

### ISSUE THREAD

**Issue by begna112** [TheQwertiest/foo_discord_rich#67]
![image](https://github.com/user-attachments/assets/3d8b6c13-b7b9-4acf-a0f7-b8e3cd3ec6fd)
![image](https://github.com/user-attachments/assets/952475c9-e1da-4d21-9781-e2ca6665d640)

This used to work, but doesn't seem to now. Updated from 1.2.1 to 2.0.2. (Granted, 1.2.1 wasn't working at all anymore.)

**Comment by skyisthela** [comment]
same issue here, the %playback_time% syntax is also wonky and unreliable :p

**Comment by PlaylistsTrance** [comment]
See the patch notes for v2.0.0 https://github.com/TheQwertiest/foo_discord_rich/releases/tag/v2.0.0
It has something to do with limitations of the Discord API. However, seemingly Discord is planning to add time bar support in the future: https://github.com/discord/discord-api-docs/pull/7033#issuecomment-2254222844

**Comment by skyisthela** [comment]
> See the patch notes for v2.0.0 https://github.com/TheQwertiest/foo_discord_rich/releases/tag/v2.0.0 It has something to do with limitations of the Discord API. However, seemingly Discord is planning to add time bar support in the future: [discord/discord-api-docs#7033 (comment)](https://github.com/discord/discord-api-docs/pull/7033#issuecomment-2254222844)

alright, thanks for the insight

**Comment by TheQwertiest** [comment]
Yea, track duration was only available in old "Playing a game" activity type and is not available in "Listening to" type.
It's possible to add an option to use old activity type (and thus activity time), but for now I'm not sure I want to do that (because "Playing a game foobar2000" is so janky :D).

PS: `%playback_time%` and other very dynamic fields can't be relied upon, since Rich Presense updates are heavily throttled  by Discord (no more than once per 15 seconds).

**Comment by Otuxam3** [comment]
Now officially added and documented as per https://github.com/discord/discord-api-docs/pull/7166
The time bar is working and some got the chance to try it out as soon as it was made available. (#81)
